<?php

/**
 * @file
 * Contains service_club_event_modal.module.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\service_club_event\Entity\EventInformation;

/**
 * Implements hook_help().
 */
function service_club_event_modal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the service_club_event_modal module.
    case 'help.page.service_club_event_modal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The module to handle to the modal to connect the event to the TMP') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function service_club_event_modal_theme() {
  return [
    'service_club_event_modal' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * @param array $build
 * @param \Drupal\service_club_event\Entity\EventInformation $entity
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 * @param $view_mode
 */
function service_club_event_modal_event_information_view( array &$build, EventInformation $entity, EntityViewDisplayInterface $display, $view_mode) {
  $eventId = $entity->id();      // the ID of the event

  $linkUrl = Url::fromRoute('event_modal.modal', array('entityid' => 'top left corner of pop-up'));

  $linkUrl->setOptions([
    'attributes' => [
      'class' => ['use-ajax', 'button', 'button--small'],
      'data-dialog-type' => 'modal',
      'data-dialog-options' => Json::encode(['width' => 800]),
    ],
  ]);

  $build['modal_button'] = [
    '#type' => 'markup',
    '#markup' => Link::fromTextAndUrl(t('Open TMP Tool'), $linkUrl)
      ->toString(),
    '#attached' => [
      'library' => [
        'core/drupal.dialog.ajax',
      ],
    ],
  ];

  // Load the jwtAuth service and generate a token.
  // Make sure your website has a key set in the JWT admin page.
  $jwtAuth = \Drupal::service('jwt.authentication.jwt');
  $jwtKey = $jwtAuth->generateToken();
  $baseUrl = \Drupal::request()->getBaseUrl();

  $build['#attached']['drupalSettings']['app_data']['jwtkey'] = $jwtKey;
  $build['#attached']['drupalSettings']['app_data']['eventid'] = $eventId;
  $build['#attached']['drupalSettings']['app_data']['baseurl'] = $baseUrl;
}
